version: 0.0
os: linux
files:
  - source: /
    destination: /opt/server/msd/mdm/zhdmdm
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: /opt/server/msd/mdm/zhdmdm/Start.sh
      timeout: 300
      runas: ec2-user